package com.example.aishwarya.melotto;

import com.parse.ParseClassName;
import com.parse.ParseFile;
import com.parse.ParseObject;

import java.io.File;
import java.util.List;

/**
 * Each User should have an array of LotteryTickets.
 * The User class ideally serves as the Model in the MVC architecture because
 * changes the User makes to his/her tickets (i.e. add tickets, delete tickets, edit tickets)
 * is what will cause the User's dashboard to refresh.
 *
 * But how to link the ParseUser that Parse creates through Facebook Authentication to an array of
 * LotteryTickets?
 *
 * Created by Aishwarya on 12/13/2015.
 */
@ParseClassName("LotteryTicket")
public class LotteryTicket extends ParseObject {

    private String lotteryName;
    private String lotteryDrawDate;
    private List<Integer> lotteryTicketNumbers;
    private File lotteryTicket;
    private ParseFile photo;

    /**
     * Constructor for the LotteryTicket class.
     * @param name
     * @param date
     * @param numbers
     */
    public LotteryTicket(String name, String date, List<Integer> numbers, File ticket)
    {
        lotteryName = name;
        lotteryDrawDate =  date;
        lotteryTicketNumbers = numbers;
        lotteryTicket = ticket;

    }

    /**
     * Taken from Parse MealSpotting app tutorial.
     * But how to link the ParseFile to a unique user ID generated by Parse?
     * The tutorial does not demonstrate this functionality.
     *
     * @return ParseFile
     */
    public ParseFile getPhotoFile() {
        return getParseFile("photo");
    }

    /**
     * Taken from Parse MealSpotting app tutorial.
     * But how to link the ParseFile to a unique user ID generated by Parse?
     * The tutorial does not demonstrate this functionality.
     *
     * @return ParseFile
     */
    public void setPhotoFile(ParseFile file) {
        put("photo", file);
    }

}
